### ISSUE TITLE
运行mirror_julia.py脚本报错：OSError: [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by ghost** [sunoru/PkgMirrors.jl#2]
```shell
huangxi@jianixbox 19:52:34 ~/develop/julia/julia_mirror $ python mirror_julia.py repo/
[2018-10-05 19:52:38]ERROR:Failed to update releases
Traceback (most recent call last):
  File "mirror_julia.py", line 556, in <module>
    main()
  File "mirror_julia.py", line 546, in main
    try_update('releases', update_releases, config, status)
  File "mirror_julia.py", line 537, in try_update
    raise e
  File "mirror_julia.py", line 532, in try_update
    update(config, status)
  File "mirror_julia.py", line 281, in update_releases
    meta = fetch_releaseinfo(config, status)
  File "mirror_julia.py", line 264, in fetch_releaseinfo
    download(Config.REMOTE_RELEASEINFO, config.releaseinfo_file, *config.logging_args)
  File "mirror_julia.py", line 119, in download
    os.rename(f.name, filename)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp2jof9gde' -> '/home/huangxi/develop/julia/julia_mirror/repo/releases/releaseinfo.json'
```
没细看脚本具体如果运作的，但是似乎是在尝试跨设备建立硬链接？
按照[一些讨论](https://github.com/PolicyStat/terrarium/pull/48)把os.rename环城shutil.move就可以解决问题

**Comment by sunoru** [comment]
嗯是的，你可以试一下手动把`os.rename`改成`shutil.move`，之后有空我测试一下再改。

**Comment by sunoru** [comment]
Fixed by https://github.com/sunoru/julia-mirror/commit/65da12172ccb4b1a72c55e68a321119f99481b36

关于配置 julia 镜像站的问题下次最好在 https://github.com/sunoru/julia-mirror 里提 issue，感谢~
